title: Drew Ciampa # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. and MBA Student at Texas Christian University 
  <br><br>
  <a href="/pdf/ciampaDrewResume.pdf">My Resume</a> 
  <br><br>
  <a href="/posts/firstpost">My Blog</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/drewciampa/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
